### ISSUE TITLE
Installing on Ubuntu

### ISSUE THREAD

**Issue by brenoc** [vtex/toolbelt-dotnet#38]
I'm trying to install the toolbet-dotnet on Ubuntu, but there are no instructions.

What steps should I follow to install it?

**Comment by rdumont** [comment]
As of now we don't have an installation process for platforms other than Windows, even though the toolbelt works on Linux and (hopefully) Mac OS X.

We are thinking about packaging the binaries as an NPM package, so that it would be 100% cross-platform.
