### ISSUE TITLE
Create .gitignore like for sync

### ISSUE THREAD

**Issue by brenoc** [vtex/toolbelt-dotnet#41]
I'm working with the Toolbelt on Ubuntu and I need to keep a reference to the Toolbelt on my root directory like this:

```sh
mystore/
├── storefront/
├── meta.json
└── vtex.sh 
```
(as in #39)

The problem is, once `vtex sync` is running I have two options: download the remote files, that will delete my local files (i.e. `vtex.sh`), or upload local files, that will upload my `vtex.sh` and this is not desirable.

What I propose is to create a .gitignore file to ignore those files that I just want to keep localy.

**Comment by firstdoit** [comment]
.storeignore

2015-02-20 13:12 GMT-02:00 Breno Calazans <notifications@github.com>:

> I'm working with the Toolbelt on Ubuntu and I need to keep a reference to
> the Toolbelt on my root directory like this:
>
> mystore/
> ├── storefront/
> ├── meta.json
> └── vtex.sh
>
> (as in #39 <https://github.com/vtex/toolbelt-dotnet/pull/39>)
>
> The problem is, once vtex sync is running I have two options: download
> the remote files, that will delete my local files (i.e. vtex.sh), or
> upload local files, that will upload my vtex.sh and this is not desirable.
>
> What I propose is to create a .gitignore file to ignore those files that I
> just want to keep localy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vtex/toolbelt-dotnet/issues/41>.
>



-- 
Att,
Guilherme Rodrigues - VTEX - Developer
lab.vtex.com
+55 21 9 88447814

Colabore com o pacote de dados do meu celular. Não utilize imagens em sua
assinatura.

**Comment by rdumont** [comment]
I think `.vtexignore` would be better. Let's do it!

**Comment by firstdoit** [comment]
.dumontignore

2015-02-20 14:23 GMT-02:00 Rodrigo Dumont <notifications@github.com>:

> I think .vtexignore would be better. Let's do it!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vtex/toolbelt-dotnet/issues/41#issuecomment-75266143>.
>



-- 
Att,
Guilherme Rodrigues - VTEX - Developer
lab.vtex.com
+55 21 9 88447814

Colabore com o pacote de dados do meu celular. Não utilize imagens em sua
assinatura.

**Comment by rdumont** [comment]
The project is now abandoned.
